### PR TITLE
176 empty json structure

### LINKED ISSUE #176: [back] [swagger] Delete Method returns empty JSON structure
Delete User returns empty JSON structure and the swagger is documented with a JSON structure of User properties.

### PR DESCRIPTION
**Pull request by Draeggon**
fix #176 
i think  it is the only way to do it
the the doc: https://flask-apispec.readthedocs.io/en/latest/usage.html#decorators

### CODE REVIEW

**Review by Benvii — COMMENTED** [review]
Great, should be applied to Room and Message also ? can you do it please. Thanks in advance.

**Comment by Draeggon** [comment]
@Benvii  yes but there is a slight problem the swagger show this:
image
and the actual response is:
image

**Comment by Benvii** [comment]
204 has no description, for me it means no response moreover the status code 204 is pretty explicit and means "No content", I know the line `default` could be confusing but for me it's not an issue as the line 204 is correct.

**Review by Benvii — APPROVED** [review]
Approve it solves the ticket, if more need to be done new issue will be needed.

**Comment by Benvii** [comment]
I will wait for your approval to merge it.

**Comment by Draeggon** [comment]
yes but the status code returned is 200 not 204

**Comment by Benvii** [comment]
We will create a issue if needed if someone wants to have a 204

**Pull request merged**
