### PR TITLE
200 Fix mistake

### LINKED ISSUE #200: [back] urgent fix landerneRPI mistakes
```py
from scratchy_server.model.messageModel import MessageModel, MessageSchema, AllMessageSchema
```
has been remove from messageres.py
```py
from scratchy_server.model.userModel import UserModel, UserSchema, AllUserSchema
```
has been remove from userres.py

### PR DESCRIPTION
**Pull request by Draeggon**
fix #200

### CODE REVIEW

**Comment by yannis-mlgrn** [comment]
see CONTRIBUTING.md, your title don't respect this

**Comment by Draeggon** [comment]
yep because you haven't done what i said in the review

**Comment by yannis-mlgrn** [comment]
this title respect CONTRIBUTING.md

**Review by yannis-mlgrn — APPROVED** [review]

**Comment by Draeggon** [comment]
@yannis-mlgrn  do you look at messages ?

**Review by Benvii — APPROVED** [review]
Ok thanks for the fix

**Pull request merged**
