### PR TITLE
#219 : Solve error in README.md

### LINKED ISSUE #219: [Doc] Error in README.md
we have two times "how to start it" in Readme.md, replace the first (link to template image) by "template image"
and in frontend README.md the link to how to start it is broken, it should be http://localhost:8000/src

### PR DESCRIPTION
**Pull request by yannis-mlgrn**
fixes #219

### CODE REVIEW

**Review by Draeggon — CHANGES_REQUESTED** [review]
look in the issue, i  have added other things in it a few days ago

**Comment by Draeggon** [comment]
@yannis-mlgrn 
image

**Comment by yannis-mlgrn** [comment]
ok

**Comment by Benvii** [comment]
Assigned to @Draeggon

**Pull request closed without merging**
