### PR TITLE
resolves #129 and #130

### LINKED ISSUE #129: [doc] replace old emoji by a new version
in scratchy, to import a python, javaScript, emoji view. We need to create a directory with an emoji picture, but I have creating a site that hosts programming language emojies like python, javaScript, html and more.
The purpose of this issue is to replace the old emoji with a new version taken from my repository.

**Link :** 

-  https://github.com/yannis-mlgrn/codmoji

### PR DESCRIPTION
**Pull request by mpsb**

### CODE REVIEW

**Review by yannis-mlgrn — DISMISSED** [review]
Good job @mpsb !

**Review by Draeggon — CHANGES_REQUESTED** [review]
nice but next time close only one issue by pr
and you should also change the html logo in  /doc/frontend/frontend.md

**Comment by mpsb** [comment]
> nice but next time close only one issue by pr
> and you should also change the html logo in /doc/frontend/frontend.md

Thank you @Draeggon, will do it next time! I've also updated the html logos as requested.

**Review by Draeggon — APPROVED** [review]

**Review by yannis-mlgrn — CHANGES_REQUESTED** [review]
Do you have remove [logos](https://github.com/mdl29/scratchy/tree/main/logos) directory because inside him have all old logos. After I think we can merge this pull request

**Comment by mpsb** [comment]
> @mpsb, do you have remove [logos](https://github.com/mdl29/scratchy/tree/main/logos) directory because inside him have all old logos ? After I think we can merge this pull request

Sure thing!

**Comment by yannis-mlgrn** [comment]
> Sure thing!

ok nice !

**Review by yannis-mlgrn — APPROVED** [review]

**Comment by yannis-mlgrn** [comment]
@mpsb, you can make a squash and merge now

**Review by Draeggon — APPROVED** [review]

**Comment by Draeggon** [comment]
@yannis-mlgrn settings have been updated now we need at list 2 good reviews to merge

**Comment by yannis-mlgrn** [comment]
@Draeggon go approve !!! 🤣

**Comment by mpsb** [comment]
> @mpsb, you can make a squash and merge now

@yannis-mlgrn But Github says only those with write access can merge?

**Comment by yannis-mlgrn** [comment]
ok I merge

**Pull request merged**
